server:
  port: 18091
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:18081/eureka/
spring:
  application:
    name: customer