#eureka的端口号
server:
  port: 18083
eureka:
  instance:
    hostname: localhost
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:18081/eureka/,http://localhost:18082/eureka/,http://localhost:18083/eureka/